import { writable } from 'svelte/store';

export const mapConfig = writable({
  "title": "How do European pupils perform in reading?",
  "subtitle": "With 500 points in the 2025 PISA test, Ireland tops the EU rankings in reading, while Cyprus is last at 379. The EU-wide average stands at around 451 points, ten points below the OECD average of 461.",
  "colourSchemeClasses": 7,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nAustria,AT,467,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nBelgium,BE,466,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nBulgaria,BG,387,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nCroatia,HR,453,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nCyprus,CY,379,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nCzechia,CZ,468,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nDenmark,DK,460,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nEstonia,EE,499,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nFinland,FI,474,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nFrance,FR,456,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nGermany,DE,465,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nGreece,EL,423,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nHungary,HU,452,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nIreland,IE,500,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nItaly,IT,474,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nLatvia,LV,430,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nLithuania,LT,464,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nLuxembourg,LU,443,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nMalta,MT,415,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nNetherlands,NL,441,false,\"Caution: one or more PISA sampling standards were not met; interpret the estimate with care.\",OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nPoland,PL,482,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nPortugal,PT,462,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nRomania,RO,413,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nSlovakia,SK,448,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nSlovenia,SI,445,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nSpain,ES,451,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nSweden,SE,466,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,",
  "parsedData": [
    {
      "country": "Austria",
      "id": "AT",
      "value": 467,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Belgium",
      "id": "BE",
      "value": 466,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 387,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 453,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 379,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 468,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 460,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 499,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 474,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 456,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 465,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 423,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 452,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 500,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 474,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 430,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 464,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 443,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 415,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 441,
      "extraInfo": false,
      "text_content": "Caution: one or more PISA sampling standards were not met; interpret the estimate with care.",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 482,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 462,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 413,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 448,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 445,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 451,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 466,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "fullNumbers",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "orange",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": true,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "OECD (2026)",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "PISA assesses 15-year-old pupils' ability to apply their knowledge and skills to tackle real-life challenges. Reading performance has fallen particularly sharply across the OECD, 14 points lower than in 2022 and 28 points below the 2015 level of 489. The EU figure of 451 points is an unweighted average of the 27 national mean scores, and does not constitute an official OECD aggregate for the EU.",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "colorBarFirstValue": "370",
  "colorBarLastValue": "500",
  "customUnitLabelAvailable": false,
  "customUnitLabel": "",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "How do European pupils perform in reading?",
    "subtitle": "With 500 points in the 2025 PISA test, Ireland tops the EU rankings in reading, while Cyprus is last at 379. The EU-wide average stands at around 451 points, ten points below the OECD average of 461.",
    "textNoteDescription": "Note",
    "textNote": "PISA assesses 15-year-old pupils' ability to apply their knowledge and skills to tackle real-life challenges. Reading performance has fallen particularly sharply across the OECD, 14 points lower than in 2022 and 28 points below the 2015 level of 489. The EU figure of 451 points is an unweighted average of the 27 national mean scores, and does not constitute an official OECD aggregate for the EU.",
    "textSourceDescription": "Source",
    "textSource": "OECD (2026)",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here",
    "extraInfo_NL": "Caution: one or more PISA sampling standards were not met; interpret the estimate with care."
  },
  "clusters": [],
  "colorScale": null,
  "extraInfo_NL": "Caution: one or more PISA sampling standards were not met; interpret the estimate with care."
});
